In [4]:
import numpy as np

In [86]:
empty_array= np.empty((2,2))
ones_array = np.ones((4,2))
print(empty_array)
print(ones_array)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [90]:
x = np.full((2,2),7)
print(x)

[[7 7]
 [7 7]]


In [96]:
y = np.zeros_like((2,2))
print(y)

[0 0]


In [105]:
z = np.ones_like((2,2))
z

array([1, 1])

In [104]:
new_list = [1,2,3,4]
new = np.array(new_list)
new


array([1, 2, 3, 4])

In [107]:
new_list = [1,2,3,4]
new = np.array(new_list)
print(new)

[1 2 3 4]


In [110]:
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [120]:
a = np.array([2,2,3,5,67,8,9,2])
np.reshape(a,(2,4))

array([[ 2,  2,  3,  5],
       [67,  8,  9,  2]])

In [123]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
a = np.random.random([30])
print(np.mean(a))

0.4382064804536738


In [24]:
a = np.random.random([10,10])

print(np.max(a))
print(np.min(a))

0.9990023566013772
0.00226325183563314


In [26]:
a = np.zeros([10])
a[4]=1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [28]:
arr = [1,2,0,0,4,0]
print (arr[::-1])

[0, 4, 0, 0, 2, 1]


In [31]:


arr = np.ones((5, 5))     # create all 1s
arr[1:-1, 1:-1] = 0        # set inside to 0

print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1


In [39]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(v.dot(w))
print(x.dot(y))
print(np.concatenate((x,y),axis=0))
print(np.concatenate((x,y),axis=1))

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[0.2        0.33333333]
 [0.42857143 0.625     ]]
219
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]


In [44]:
A = np.array([[3,4],[7,8]])
B= np.array([[5,3],[2,1]])
a_inverse = np.linalg.inv(A)
A @ a_inverse

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [46]:
print (A @ B )
B @ A

[[23 13]
 [51 29]]


array([[36, 44],
       [13, 16]])

In [53]:
ab_inv = np.linalg.inv(A @ B)
print ( np.linalg.inv(B) @ np.linalg.inv(A) )
ab_inv


[[  7.25  -3.25]
 [-12.75   5.75]]


array([[  7.25,  -3.25],
       [-12.75,   5.75]])

In [54]:
A = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)   # find A inverse

X = A_inv @ B              # matrix multiplication

print("A inverse:\n", A_inv)
print("\nSolution vector X = [x, y, z]:\n", X)


A inverse:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution vector X = [x, y, z]:
 [ 2.  1. -2.]
